
const UsoDeCookies = () => (
    <div className="container mx-auto">
        <div className='text-3xl font-bold'>Políticas de uso de cookies </div>
        <p style={{marginTop: '0.2em'}}>Este aviso es emitido por Vali Wealth Tech, S.A.P.I. de C.V. sus filiales y/o subsidiarias, y/o sus partes relacionadas (“Vali”), con domicilio en Lázaro Garza Ayala 1214, Interior 1, Colonia Palo Blanco, San Pedro Garza García, Nuevo León, C.P. 66236, dirección electrónica: https://heyvali.com (el “Sitio”) y con correo electrónico de contacto [privacidad@vali.com] (el “Correo Electrónico”), con la finalidad de dar a conocer a cualquier persona que acceda o haga uso del Sitio (el “Usuario”), el uso de cookies que hace Vali en el mismo.</p>
        <p style={{marginTop: '0.2em'}}>Las partes entenderán como cookies, aquellos archivos cortos que habitualmente consisten en letras y números, que se colocan en la computadora, tablet, teléfono o dispositivo similar que el Usuario utilice para acceder al Sitio (“cookies”) y/o aquellas tecnologías similares, como etiquetas de píxel, balizas web, GIF transparentes, JavaScript y almacenamiento local (“balizas web”), que puedan estar relacionadas con el Sitio.</p>
        <p style={{marginTop: '0.2em'}}>El acceso y/o uso del Sitio implica la aceptación plena de los términos aquí contenidos. En consecuencia, es responsabilidad única y exclusiva del Usuario, leer previamente esta política de uso y sus modificaciones correspondientes, cada vez que accede al Sitio. Si en cualquier momento, el Usuario no estuviera de acuerdo total o parcialmente con los presentes términos, deberá, a su criterio, deshabilitar las cookies establecidas o abstenerse inmediatamente de usar el Sitio.</p>
        <div className='text-xl mt-4 font-bold'>OBJETO</div>
        <p style={{marginTop: '0.2em'}}>Con la finalidad de proporcionar al Usuario la mejor funcionalidad posible del Sitio e información personalizada adecuada a sus intereses, Vali sus socios y/o aliados, podrán hacer uso de cookies, para recopilar datos que permitan brindar información analítica, así como la identificación personal, o que podría permitir la identificación personal bajo la combinación con otra información, en cuyo caso, se considerará regido bajo los términos establecidos en el Aviso de Privacidad de Vali y en el presente documento.</p>
        <p style={{marginTop: '0.2em'}}>Vali, como operador del Sitio, puede poner cookies en el dispositivo por el cual el Usuario accede a este. Estas cookies se llaman cookies “de origen”. Las cookies dispuestas por proveedores que presten servicios a través del Sitio, tales como correo electrónico, se les llama “de terceros”. Vali no controla el uso de esta tecnología, o la información resultante, y no es responsable por ninguna acción o política de esas terceras partes.</p>
        <p style={{marginTop: '0.2em'}}>Vali hace del conocimiento del Usuario que, por medio de las cookies, es posible obtener y utilizar información agregada y de otro tipo que NO IDENTIFICA a los Usuarios individuales (como su sistema operativo, su versión de navegador y la URL de origen, incluidos mensajes de correo electrónico y anuncios publicitarios) para mejorar su experiencia y comprender los patrones de tráfico. Esta tecnología se utiliza como una herramienta para compilar estadísticas agregadas acerca del uso del Sitio para análisis y desempeño y optimización del mismo.</p>
        <p style={{marginTop: '0.2em'}}>Vali manifiesta que puede también hacer uso de tecnologías similares, como las balizas web (a veces llamadas “píxeles de seguimiento” o “GIF transparentes”). Estos son archivos gráficos, muy pequeños, contienen un identificador único que permite reconocer la visita al Sitio o notificar a Vali cuando el Usuario abra un correo electrónico que haya sido enviado por Vali. Generalmente, estas tecnologías se sustentan en cookies para que funcionen de manera correcta, por lo que su disminución afecta directamente su funcionamiento.</p>
        <div className='text-xl font-bold'>TIPO DE COOKIES</div>
        <p style={{marginTop: '0.2em'}}>Vali y sus proveedores de servicios podrán hacer uso de uno o más tipos de cookies, en adelante descritas:</p>
        <p style={{marginTop: '0.2em'}}>Cookies esenciales. Requeridas para mejorar el funcionamiento del Sitio, permitiendo al Usuario recorrer el Sitio y hacer uso de sus características (por ejemplo, para permitirle al Usuario iniciar sesión en áreas seguras del Sitio o utilizar un carro de compras). La deshabilitación de estas cookies provocará un entorpecimiento del desempeño del Sitio, y posiblemente dejará sin disponibilidad las características del Sitio y su servicio.</p>
        <p style={{marginTop: '0.2em'}}>Cookies de análisis y personalización. Diseñadas para analizar la actividad del Usuario en el Sitio y/o en los sitios donde Vali publique o promocione contenidos, mismas que se usan para asegurar que el Usuario pueda encontrar la información que busca en el Sitio de una manera más fácil. Estas cookies permiten el reconocimiento y contabilización de visitantes al Sitio, así como la medición del desempeño de campañas publicitarias y optimización del contenido del Sitio por parte de Vali.</p>
        <p style={{marginTop: '0.2em'}}>Cookies de funcionalidad. Utilizadas para reconocer al Usuario cuando ingresa o regresa al Sitio de Vali, mediante la personalización del Contenido, uso del nombre registrado como Usuario y preferencias tales como: idioma, región, etc.</p>
        <p style={{marginTop: '0.2em'}}>Cookies de publicidad. Estas cookies son utilizadas con el objeto de resaltar el contenido del Sitio que sea más relevante para el Usuario, en función de los intereses aparentes recopilados según su actividad en línea, incluidas las visitas al Sitio, las páginas que ha visitado y la selección de enlaces y anuncios. Lo anterior permite que, mediante el uso de plataformas de administración y edición de datos, se enlacen avisos publicitarios en el Sitio propiedad de Vali o en cualquier otro, con la finalidad de mantener una promoción continua de los productos y servicios visitados en el Sitio.</p>
        <p style={{marginTop: '0.2em'}}>DEL USO DE COOKIES. El uso de cookies permite a Vali, y a sus proveedores de servicio, recabar ciertos datos sensibles del Usuario a fin de: i) obtener información acerca de sus visitas al Sitio; ii) procesar los pedidos del Usuario; iii) analizar sus patrones de visita para mejoras del Sitio; iv) ofrecer publicidad, comunicaciones y contenidos de Vali y de terceros aliados en el Sitio y en el de terceros que sean específicos en relación con sus intereses; v) recordar el idioma y otras preferencias del Usuario; vi) ayudar al Usuario a obtener la información que busca; vii) ofrecer un servicio seguro para las transacciones en línea; viii) cuantificar el acceso y uso del Sitio; ix) ofrecer una funcionalidad eficaz y en concordancia a la audiencia del Sitio, entre otros.</p>
        <p style={{marginTop: '0.2em'}}>El registro de información personal por parte del Usuario en el Sitio, permite a Vali que, por medio de la asociación de dicha información con otra información que se recabe a través de terceros que se encuentre directa o indirectamente relacionada con el uso del Sitio, se use la misma con fines de análisis y de mercadeo, siempre estadística y no individualizada.</p>
        <p style={{marginTop: '0.2em'}}>TIPOS DE COOKIES RESPECTO A SUS PERMANENCIA EN EL SISTEMA. La función y permanencia de las cookies en el sistema del dispositivo a través del cual se acceda al Sitio, pueden ser:</p>
        <p style={{marginTop: '0.2em'}}>“De sesión”, las cuales se activan en el momento de su acceso al Sitio y hasta la finalización de esa sesión. Estas cookies vencen y se eliminan automáticamente cuando se cierra el navegador de Internet; o</p>
        <p style={{marginTop: '0.2em'}}>“Persistentes” las cuales permanecen en el dispositivo de acceso al Sitio entre sesiones de navegación. La cantidad de tiempo que una cookie persistente permanece en su dispositivo varía de una cookie a otra.</p>
        <p style={{marginTop: '0.2em'}}>El propósito para el cual Vali hace uso de cookies es: i) para almacenamiento de preferencias del Usuario, con la finalidad de mantenerlas disponibles para su próxima visita; ii) para mantener información de frecuencia y variación en tiempo de visita al Sitio; y iii) para probar la eficacia de los esfuerzos de publicidad.</p>
        <div className='text-xl mt-4 font-bold'>ADMINISTRACIÓN DE COOKIES POR EL USUARIO.</div>
        <p style={{marginTop: '0.2em'}}>El Usuario, a través de la configuración de su navegador de Internet, podrá decidir si desea o no aceptar cookies del Sitio. Vali manifiesta que, el bloqueo por parte del Usuario de todas las cookies, puede provocar el bloqueo o afectación total o parcial en el acceso y uso del Sitio.</p>
        <p style={{marginTop: '0.2em'}}>Vali se compromete a hacer buen uso de los datos personales y datos sensibles provistos por el Usuario, y que lo hará conforme al Aviso de Privacidad que se encuentra en el Sitio. Cualquier duda o comentario respecto al uso de cookies por parte de Vali, puede ser dirigida al Correo Electrónico. En dicho caso, favor de incluir la información de contacto, el nombre del sitio web de Vali y una descripción detallada de la solicitud o preocupación relacionada con las cookies.</p>
        <div className='text-xl mt-4 font-bold'>ACEPTACIÓN DE LOS TÉRMINOS.</div>
        <p style={{marginTop: '0.2em'}}>El Usuario reconoce que, mediante el acceso y uso del Sitio, manifiesta su aceptación plena y sin reservas y, por tanto, su adhesión a la versión de estos términos publicada en el momento en que acceda al Sitio, en términos de lo establecido por los artículos 1803 y 1834 Bis del Código Civil Federal, 80, 81, 89 y demás relativos y aplicables del Código de Comercio y la legislación aplicable para México. Es responsabilidad única y exclusiva del Usuario, leer previamente estos términos y sus modificaciones correspondientes, cada vez que accede al Sitio. Si, en cualquier momento, el Usuario no estuviera de acuerdo, total o parcialmente con los presentes términos, deberá abstenerse inmediatamente de acceder y usar el Sitio. Por lo anterior, con la aceptación de los presentes términos, el Usuario consiente expresamente sujetarse a los mismos, por lo que manifiesta haber leído el contenido de todas y cada una de las disposiciones y ratifica su contenido.</p>
        <div className='text-xl mt-4 font-bold'>ACUERDO TOTAL.</div>
        <p style={{marginTop: '0.2em'}}>El Usuario reconoce y acepta que Vali puso a su disposición toda la información para entender el alcance y características del Sitio. De igual forma manifiesta que, previo al acceso al Sitio, analizó las características de éste y, por consiguiente, está de acuerdo con ellas.</p>
        <p style={{marginTop: '0.2em'}}>Fecha de primera emisión: [29/11/2022].</p>

    </div>
)

export default UsoDeCookies;
